package de.escidoc.admintool.view.orgunit;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.Label;
import com.vaadin.ui.Panel;

public class BlankPredessorView extends CustomComponent {

    private Panel mainLayout;

    /**
     * The constructor should first build the main layout, set the composition
     * root and then do any custom initialization.
     * 
     * The constructor will not be automatically regenerated by the visual
     * editor.
     */
    public BlankPredessorView() {
        buildMainLayout();
        setCompositionRoot(mainLayout);
        mainLayout.addComponent(new Label("BlankPredeccesorView"));
    }

    @AutoGenerated
    private void buildMainLayout() {
        mainLayout = new Panel();
        mainLayout.setWidth("400px");
    }
}
