package de.escidoc.admintool.view.orgunit;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.Label;
import com.vaadin.ui.Panel;

public class SpinOffPredessorView extends CustomComponent {

    @AutoGenerated
    private Panel mainLayout;

    /**
     * The constructor should first build the main layout, set the composition
     * root and then do any custom initialization.
     * 
     * The constructor will not be automatically regenerated by the visual
     * editor.
     */
    public SpinOffPredessorView() {
        buildMainLayout();
        setCompositionRoot(mainLayout);
        mainLayout.addComponent(new Label("SpinOffPredessorView"));
    }

    @AutoGenerated
    private void buildMainLayout() {
        // the main layout and components will be created here
        mainLayout = new Panel();
    }

}
