package de.escidoc.admintool.view.context;

import java.util.Collection;
import java.util.Iterator;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.Panel;
import com.vaadin.ui.Tree;
import com.vaadin.ui.themes.Reindeer;

import de.escidoc.admintool.service.OrgUnitService;
import de.escidoc.core.client.exceptions.EscidocException;
import de.escidoc.core.client.exceptions.InternalClientException;
import de.escidoc.core.client.exceptions.TransportException;
import de.escidoc.core.resources.oum.OrganizationalUnit;
import de.escidoc.core.resources.oum.Parent;
import de.escidoc.core.resources.oum.Parents;
import de.escidoc.vaadin.utilities.TreeHelper;

public class OrgUnitTree extends CustomComponent {
    private static final long serialVersionUID = 671280566874568107L;

    private final Tree tree = new Tree();

    private final OrgUnitService service;

    private final Logger log = LoggerFactory.getLogger(OrgUnitTree.class);

    // private OrganizationalUnit rootNode;
    private String rootNode;

    private Iterator<Parent> iterator;

    /**
     * The constructor should first build the main layout, set the composition
     * root and then do any custom initialization.
     * 
     * The constructor will not be automatically regenerated by the visual
     * editor.
     * 
     * public OrgUnitTree() { Panel panel = new Panel();
     * panel.setStyleName(Reindeer.PANEL_LIGHT); tree.setHeight(null);
     * tree.setWidth("100%"); tree.setMultiSelect(true);
     * tree.setImmediate(true); loadFakeTreeData(); panel.addComponent(tree);
     * setCompositionRoot(panel); } /**
     * 
     */
    public OrgUnitTree(OrgUnitService service) {
        this.service = service;
        Panel panel = new Panel();
        panel.setStyleName(Reindeer.PANEL_LIGHT);
        tree.setHeight(null);
        tree.setWidth("100%");
        tree.setMultiSelect(true);
        tree.setImmediate(true);
        panel.addComponent(tree);
        setCompositionRoot(panel);
        loadOrgUnits();
    }

    public void setMultiSelect(boolean multiSelect) {
        tree.setMultiSelect(multiSelect);
    }

    /**
     * Replace me by a call of the service.
     */
    private void loadOrgUnits() {
        try {
            Collection<OrganizationalUnit> col =
                service.getOrganizationalUnits();
            tree.removeAllItems();

            for (OrganizationalUnit child : col) {
                Parents parents = child.getParents();
                if (parents != null) {
                    Collection<Parent> parentRef = parents.getParentRef();
                    if (parentRef != null) {
                        iterator = parentRef.iterator();
                        if (iterator.hasNext()) {
                            Parent parent = iterator.next();
                            TreeHelper.addChildren(tree, parent, child, true);
                        }
                        else {
                            TreeHelper.addChildren(tree, child, true);
                        }
                    }
                    else {
                        TreeHelper.addChildren(tree, child, true);
                    }
                }
                else {
                    TreeHelper.addChildren(tree, child, true);
                }
            }
        }
        catch (InternalClientException e) {
            log.error("An unexpected error occured! See log for details.", e);
            e.printStackTrace();

        }
        catch (TransportException e) {
            log.error("An unexpected error occured! See log for details.", e);
            e.printStackTrace();

        }
        catch (EscidocException e) {
            log.error("An unexpected error occured! See log for details.", e);
            e.printStackTrace();
        }
    }

    private void loadFakeTreeData() {
        String rootOrg = "External Organizations";
        tree.addItem(rootOrg);

        Object[] extOrg =
            new Object[] { "Angelo State University",
                "Berlin University of the Arts", "Bond University",
                "Brandeis University", "Bryn Mawr College",
                "Cardiff University", "..." };

        for (Object o : extOrg) {
            tree.addItem(o);
            // Set it to be a child.
            tree.setParent(o, rootOrg);
            // Make the moons look like leaves.
            tree.setChildrenAllowed(o, false);
        }

        rootOrg = "Kaiser-Wilhelm-Gesellschaft";
        tree.addItem(rootOrg);
        String child =
            "Kaiser Wilhelm Institut für Züchtungsforschung (geschlossen)";
        tree.addItem(child);
        // Set it to be a child.
        tree.setParent(child, rootOrg);
        // Make the moons look like leaves.
        tree.setChildrenAllowed(child, false);

        rootOrg = "Max Planck Society";
        tree.addItem(rootOrg);

        extOrg =
            new Object[] { "Fritz Haber Institute",
                "Max Planck Digital Library", "MPI for Astrophysics",
                "MPI for biophysical chemistry", };

        for (Object o : extOrg) {
            tree.addItem(o);
            // Set it to be a child.
            tree.setParent(o, rootOrg);
            // Make the moons look like leaves.
            tree.setChildrenAllowed(o, false);
        }
        Object subParent = "MPI for Chemical Ecology";
        tree.addItem(subParent);
        tree.setParent(subParent, rootOrg);
        tree.setChildrenAllowed(subParent, true);
        String subUnit = "Department of Biochemistry, Prof. J. Gershenzon";
        tree.addItem(subUnit);
        // Set it to be a child.
        tree.setParent(subUnit, subParent);
        // Make the moons look like leaves.
        tree.setChildrenAllowed(subUnit, true);

        Object[] subsubUnit =
            new Object[] {
                "Research Group Dr. G. Kunert, Chemical Communication in Plant-Aphid-Interactions",
                "Research Group Dr. J. D'Auria, Biochemistry and Evolution of Tropane Alkaloid Biosynthesis",
                "Research Group Dr. S. Unsicker, Chemical Ecology of Trees" };

        for (Object o : subsubUnit) {
            tree.addItem(o);
            // Set it to be a child.
            tree.setParent(o, subUnit);
            // Make the moons look like leaves.
            tree.setChildrenAllowed(o, false);
        }

        Object[] restUnit =
            new Object[] {
                "Department of Bioorganic Chemistry, Prof. Dr. W. Boland",
                "Department of Entomology, Prof. D. G. Heckel",
                "Department of Evolutionary Neuroethology, Prof. B. S. Hansson",
                "Department of Genetics and Evolution",
                "Department of Molecular Ecology, Prof. I. T. Baldwin",
                "IMPRS on Ecological Interactions",
                "Max Planck Research Group Insect Symbiosis",
                "Research Group Biosynthesis / NMR",
                "Research Group Mass Spectrometry", "..." };

        for (Object o : restUnit) {
            tree.addItem(o);
            // Set it to be a child.
            tree.setParent(o, subParent);
            // Make the moons look like leaves.
            tree.setChildrenAllowed(o, false);
        }

        rootOrg = "物質・材料研究機構/ National Institute for Materials Science";
        tree.addItem(rootOrg);

        Object[] asia =
            new Object[] { "総務部 / General Affairs Division",
                "人事課 / Personnel Section", "契約課 / Contract Section", "..."

            };

        for (Object o : asia) {
            tree.addItem(o);
            // Set it to be a child.
            tree.setParent(o, rootOrg);
            // Make the moons look like leaves.
            tree.setChildrenAllowed(o, false);
        }
    }

    public Object getSelectedItems() {
        return tree.getValue();
    }
}