package de.escidoc.admintool.view.orgunit.predecessor;

public class BlankPredecessorView extends AbstractPredecessorView {
    private static final long serialVersionUID = 7500088834432222446L;

    // private Panel mainLayout;

    // /**
    // * The constructor should first build the main layout, set the composition
    // * root and then do any custom initialization.
    // *
    // * The constructor will not be automatically regenerated by the visual
    // * editor.
    // */
    public BlankPredecessorView() {
        buildMainLayout();
        setCompositionRoot(mainLayout);
    }

    private void buildMainLayout() {
        mainLayout.setWidth("400px");
    }
}
