package de.escidoc.admintool.view.orgunit.predecessor;

import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.Label;
import com.vaadin.ui.Panel;

public class AffiliationPredecessorView extends CustomComponent {
    private static final long serialVersionUID = 7500088834432222446L;

    private Panel mainLayout;

    /**
     * The constructor should first build the main layout, set the composition
     * root and then do any custom initialization.
     * 
     * The constructor will not be automatically regenerated by the visual
     * editor.
     */
    public AffiliationPredecessorView() {
        buildMainLayout();
        setCompositionRoot(mainLayout);
        mainLayout.addComponent(new Label("AffiliationPredeccesorView"));
    }

    private void buildMainLayout() {
        mainLayout = new Panel();
        mainLayout.setWidth("400px");
    }
}
