package de.escidoc.admintool.view.orgunit.predecessor;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.Label;
import com.vaadin.ui.Panel;

public class FusionPredecessorView extends CustomComponent {
    /**
     * 
     */
    private static final long serialVersionUID = 1L;

    @AutoGenerated
    private Panel mainLayout;

    /**
     * The constructor should first build the main layout, set the composition
     * root and then do any custom initialization.
     * 
     * The constructor will not be automatically regenerated by the visual
     * editor.
     */
    public FusionPredecessorView() {
        buildMainLayout();
        setCompositionRoot(mainLayout);
        mainLayout.addComponent(new Label("Fusion Predeccesor View"));
    }

    @AutoGenerated
    private void buildMainLayout() {
        // the main layout and components will be created here
        mainLayout = new Panel();
    }
}